### ISSUE TITLE
Tutorial file not available

### ISSUE THREAD

**Issue by JuliaSprenger** [btel/SpikeSort#97]
Hi,
the tutorial data set (https://itb.biologie.hu-berlin.de/~bartosz/spikesort/_downloads/tutorial.h5) seems not to be available. Did you move it to another location?

**Comment by belevtsoff** [comment]
@btel Could you take a look at this?

**Comment by btel** [comment]
Thanks for pointing this out. I am updating links in the docs. In the meantime you can download the file from this location: https://www.unic.cnrs-gif.fr/owncloud/index.php/s/fQC80tp6PWoUh2F/download

**Comment by btel** [comment]
fixed by 8a8c2d0
